package derekahedron.invexp.sack;

import derekahedron.invexp.registry.InvExpRegistryKeys;
import derekahedron.invexp.util.InvExpUtil;
import net.minecraft.registry.RegistryKey;

public class SackTypes {
    public static final RegistryKey<SackType> WOOD = of("wood");
    public static final RegistryKey<SackType> DOOR = of("door");
    public static final RegistryKey<SackType> PRESSURE_PLATE = of("pressure_plate");
    public static final RegistryKey<SackType> BUTTON = of("button");
    public static final RegistryKey<SackType> STONE = of("stone");
    public static final RegistryKey<SackType> BRICKS = of("bricks");
    public static final RegistryKey<SackType> MUD_BRICKS = of("mud_bricks");
    public static final RegistryKey<SackType> RESIN_BRICKS = of("resin_bricks");
    public static final RegistryKey<SackType> SANDSTONE = of("sandstone");
    public static final RegistryKey<SackType> PRISMARINE = of("prismarine");
    public static final RegistryKey<SackType> NETHER_BRICKS = of("nether_bricks");
    public static final RegistryKey<SackType> PURPUR = of("purpur");
    public static final RegistryKey<SackType> METAL_BLOCK = of("metal_block");
    public static final RegistryKey<SackType> CRYSTAL_BLOCK = of("crystal_block");
    public static final RegistryKey<SackType> BARS = of("bars");
    public static final RegistryKey<SackType> CHAINS = of("chains");
    public static final RegistryKey<SackType> WOOL = of("wool");
    public static final RegistryKey<SackType> TERRACOTTA = of("terracotta");
    public static final RegistryKey<SackType> CONCRETE = of("concrete");
    public static final RegistryKey<SackType> CONCRETE_POWDER = of("concrete_powder");
    public static final RegistryKey<SackType> GLASS = of("glass");
    public static final RegistryKey<SackType> BED = of("bed");
    public static final RegistryKey<SackType> CANDLE = of("candle");
    public static final RegistryKey<SackType> BANNER = of("banner");
    public static final RegistryKey<SackType> SOIL = of("soil");
    public static final RegistryKey<SackType> ICE = of("ice");
    public static final RegistryKey<SackType> SNOW = of("snow");
    public static final RegistryKey<SackType> BONE_BLOCK = of("bone_block");
    public static final RegistryKey<SackType> ORE = of("ore");
    public static final RegistryKey<SackType> FUNGUS = of("fungus");
    public static final RegistryKey<SackType> PLANT = of("plant");
    public static final RegistryKey<SackType> BAMBOO = of("bamboo");
    public static final RegistryKey<SackType> CHORUS_FRUIT = of("chorus_fruit");
    public static final RegistryKey<SackType> EGG = of("egg");
    public static final RegistryKey<SackType> WHEAT_SEEDS = of("wheat_seeds");
    public static final RegistryKey<SackType> COCOA_BEANS = of("cocoa_beans");
    public static final RegistryKey<SackType> PUMPKIN_SEEDS = of("pumpkin_seeds");
    public static final RegistryKey<SackType> MELON_SEEDS = of("melon_seeds");
    public static final RegistryKey<SackType> BEETROOT_SEEDS = of("beetroot_seeds");
    public static final RegistryKey<SackType> TORCHFLOWER_SEEDS = of("torchflower_seeds");
    public static final RegistryKey<SackType> PITCHER_POD = of("pitcher_pod");
    public static final RegistryKey<SackType> GLOW_BERRIES = of("glow_berries");
    public static final RegistryKey<SackType> SWEET_BERRIES = of("sweet_berries");
    public static final RegistryKey<SackType> NETHER_WART = of("nether_wart");
    public static final RegistryKey<SackType> SEA_CREATURE = of("sea_creature");
    public static final RegistryKey<SackType> KELP = of("kelp");
    public static final RegistryKey<SackType> CORAL = of("coral");
    public static final RegistryKey<SackType> SPONGE = of("sponge");
    public static final RegistryKey<SackType> MELON = of("melon");
    public static final RegistryKey<SackType> PUMPKIN = of("pumpkin");
    public static final RegistryKey<SackType> HIVE = of("hive");
    public static final RegistryKey<SackType> HONEY = of("honey");
    public static final RegistryKey<SackType> FROGLIGHT = of("froglight");
    public static final RegistryKey<SackType> SCULK = of("sculk");
    public static final RegistryKey<SackType> COBWEB = of("cobweb");
    public static final RegistryKey<SackType> BEDROCK = of("bedrock");
    public static final RegistryKey<SackType> TORCH = of("torch");
    public static final RegistryKey<SackType> LANTERN = of("lantern");
    public static final RegistryKey<SackType> END_CRYSTAL = of("end_crystal");
    public static final RegistryKey<SackType> BELL = of("bell");
    public static final RegistryKey<SackType> SCAFFOLDING = of("scaffolding");
    public static final RegistryKey<SackType> POT = of("pot");
    public static final RegistryKey<SackType> ARMOR_STAND = of("armor_stand");
    public static final RegistryKey<SackType> ITEM_FRAME = of("item_frame");
    public static final RegistryKey<SackType> PAINTING = of("painting");
    public static final RegistryKey<SackType> SIGN = of("sign");
    public static final RegistryKey<SackType> HEAD = of("head");
    public static final RegistryKey<SackType> INFESTED_STONE = of("infested_stone");
    public static final RegistryKey<SackType> REDSTONE_COMPONENT = of("redstone_component");
    public static final RegistryKey<SackType> RAIL = of("rail");
    public static final RegistryKey<SackType> MINECART = of("minecart");
    public static final RegistryKey<SackType> TNT = of("tnt");
    public static final RegistryKey<SackType> BUCKET = of("bucket");
    public static final RegistryKey<SackType> FIRE_CHARGE = of("fire_charge");
    public static final RegistryKey<SackType> BONE_MEAL = of("bone_meal");
    public static final RegistryKey<SackType> NAME_TAG = of("name_tag");
    public static final RegistryKey<SackType> LEAD = of("lead");
    public static final RegistryKey<SackType> COMPASS = of("compass");
    public static final RegistryKey<SackType> CLOCK = of("clock");
    public static final RegistryKey<SackType> MAP = of("map");
    public static final RegistryKey<SackType> WIND_CHARGE = of("wind_charge");
    public static final RegistryKey<SackType> FIREWORK_ROCKET = of("firework_rocket");
    public static final RegistryKey<SackType> SADDLE = of("saddle");
    public static final RegistryKey<SackType> BOAT = of("boat");
    public static final RegistryKey<SackType> GOAT_HORN = of("goat_horn");
    public static final RegistryKey<SackType> MUSIC_DISC = of("music_disc");
    public static final RegistryKey<SackType> TOTEM_OF_UNDYING = of("totem_of_undying");
    public static final RegistryKey<SackType> ARROW = of("arrow");
    public static final RegistryKey<SackType> FOOD = of("food");
    public static final RegistryKey<SackType> CARROT = of("carrot");
    public static final RegistryKey<SackType> POTATO = of("potato");
    public static final RegistryKey<SackType> BEETROOT = of("beetroot");
    public static final RegistryKey<SackType> RAW_FISH = of("raw_fish");
    public static final RegistryKey<SackType> BOTTLE = of("bottle");
    public static final RegistryKey<SackType> WHEAT = of("wheat");
    public static final RegistryKey<SackType> CREATURE = of("creature");
    public static final RegistryKey<SackType> HEART_OF_THE_SEA = of("heart_of_the_sea");
    public static final RegistryKey<SackType> DYE = of("dye");
    public static final RegistryKey<SackType> PAPER = of("paper");
    public static final RegistryKey<SackType> BOOK = of("book");
    public static final RegistryKey<SackType> FIREWORK_STAR = of("firework_star");
    public static final RegistryKey<SackType> SUGAR = of("sugar");
    public static final RegistryKey<SackType> BANNER_PATTERN = of("banner_pattern");
    public static final RegistryKey<SackType> POTTERY_SHERD = of("pottery_sherd");
    public static final RegistryKey<SackType> SMITHING_TEMPLATE = of("smithing_template");
    public static final RegistryKey<SackType> KEY = of("wood");
    public static final RegistryKey<SackType> SPAWN_EGG = of("spawn_egg");
    public static final RegistryKey<SackType> COMMAND_BLOCK = of("command_block");

    public static RegistryKey<SackType> of(String id) {
        return RegistryKey.of(InvExpRegistryKeys.SACK_TYPE, InvExpUtil.identifier(id));
    }
}
